# Generated by Django 4.2.3 on 2024-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libpj", "0003_profile_name_profile_surename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="borrowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="on_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
