# Generated by Django 4.2.3 on 2024-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libpj", "0006_book_author_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(default="None", max_length=40),
        ),
    ]
